FROM circleci/python:3

ENV DEBIAN_FRONTEND noninteractive
USER root
RUN apt-get update && \
	apt-get install --assume-yes --no-install-recommends \
		libxml2-dev \
		libxslt1-dev \
		&& \
	rm --recursive --force /var/lib/apt/lists/*

WORKDIR /opt/lookout_hunter
COPY ./requirements.txt ./requirements.txt
RUN pip3 install --requirement ./requirements.txt

USER circleci
ADD ./data ./data
ADD ./deploy-data.sh ./deploy-data.sh
CMD ./deploy-data.sh
